# Generated by Django 4.1 on 2023-01-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0017_userprofile_enable_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
