name: tests
run-name: Running Tests

on:
  workflow_call:
  push:
    branches-ignore:
      - develop
      - master
jobs:
  run_tests:
    name: Run Django Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Install Node dependencies
        run: npm install
      - name: Run tests
        run: python manage.py test